# Generated by Django 5.1.6 on 2026-04-03 22:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0002_agentsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="VapiAssistant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "vapi_assistant_id",
                    models.CharField(blank=True, max_length=128, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("model_provider", models.CharField(default="openai", max_length=64)),
                ("model_name", models.CharField(default="gpt-4o-mini", max_length=128)),
                ("system_prompt", models.TextField(blank=True, default="")),
                ("temperature", models.FloatField(default=0.7)),
                ("max_tokens", models.PositiveIntegerField(default=1024)),
                ("voice_provider", models.CharField(default="deepgram", max_length=64)),
                ("voice_model", models.CharField(default="aura-2", max_length=128)),
                (
                    "voice_voice_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "transcriber_provider",
                    models.CharField(default="deepgram", max_length=64),
                ),
                (
                    "transcriber_model",
                    models.CharField(default="nova-2", max_length=128),
                ),
                ("first_message", models.TextField(blank=True, default="")),
                ("end_call_phrases", models.JSONField(blank=True, default=list)),
                ("voicemail_message", models.TextField(blank=True, default="")),
                ("tools", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
