# Generated by Django 5.1.6 on 2026-04-04 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0003_vapiassistant"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AgentSettings",
        ),
        migrations.DeleteModel(
            name="VapiAssistant",
        ),
    ]
