# Generated by Django 5.1.6 on 2026-04-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0006_remove_property_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=64)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("property_address", models.TextField(blank=True, default="")),
                (
                    "property_status",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "sell_timeline",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "occupancy_status",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "call_priority",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "call_reason",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("additional_notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["phone"], name="leads_prope_phone_7506a1_idx"),
                    models.Index(fields=["email"], name="leads_prope_email_5b24d1_idx"),
                    models.Index(
                        fields=["property_address"],
                        name="leads_prope_propert_eac316_idx",
                    ),
                ],
            },
        ),
    ]
