# Generated by Django 5.1.6 on 2026-04-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0008_rename_fields"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="property",
            name="leads_prope_phone_7506a1_idx",
        ),
        migrations.RemoveIndex(
            model_name="property",
            name="leads_prope_email_5b24d1_idx",
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["caller_phone"], name="leads_prope_caller__1b6166_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["caller_email"], name="leads_prope_caller__167b9b_idx"
            ),
        ),
    ]
