# Generated by Django 5.1.6 on 2026-04-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0009_remove_property_leads_prope_phone_7506a1_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="price_listing",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
